# SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE 
# FROM REST_INFO A
# JOIN REST_REVIEW B ON A.REST_ID = B.REST_ID
# WHERE A.ADDRESS LIKE '%서울%'
# ORDER BY SCORE DESC, A.FAVORITES DESC;

SELECT REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE 
FROM REST_INFO JOIN REST_REVIEW USING(REST_ID)
GROUP BY REST_ID
HAVING ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC;


# SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) SCORE
# FROM REST_INFO JOIN REST_REVIEW USING(REST_ID)
# GROUP BY REST_NAME
# HAVING ADDRESS LIKE "서울%"
# ORDER BY SCORE DESC, FAVORITES DESC