-- 코드를 작성해주세요
SELECT ITEM_ID,ITEM_NAME,RARITY FROM ITEM_INFO
JOIN ITEM_TREE USING(ITEM_ID)
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY='RARE')
ORDER BY ITEM_ID DESC



# SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
# FROM ITEM_INFO I
# JOIN ITEM_TREE T
# USING (ITEM_ID)
# WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY='RARE')
# ORDER BY ITEM_ID DESC;